# Donot give any local system related absolute path eg. : E:\STUDY\TENSORFLOW\Projects\1_CNN_Project\src\cnn_classifier\pipeline\...
# It will throw error(s) when we run the app on the production server.
stages:

    data_ingestion: 

      cmd: python src/cnn_classifier/pipeline/Stage01_data_ingestion.py
      deps:
        - src/cnn_classifier/pipeline/Stage01_data_ingestion.py
        - config/config.yaml

      outs:
        - artifacts/data_ingestion/data

    prepare_base_model: 

      cmd: python src/cnn_classifier/pipeline/Stage02_prepare_base_model.py
    
      deps:
        - src/cnn_classifier/pipeline/Stage02_prepare_base_model.py
        - config/config.yaml
        - params.yaml

      params:
        - INPUT_SHAPE
        - INCLUDE_TOP
        - CLASSES   
        - WEIGHTS
        - LEARNING_RATE # we have given an option to use the LR but didn't use

      outs:
        - artifacts/prepare_base_model
    

    training:

      cmd: python src/cnn_classifier/pipeline/Stage03_model_trainer.py

      deps:
        - src/cnn_classifier/pipeline/Stage03_model_trainer.py
        - config/config.yaml
        - artifacts/data_ingestion/data
        - artifacts/prepare_base_model
        - params.yaml

      params:
        - INPUT_SHAPE
        - INCLUDE_TOP
        - CLASSES
        - WEIGHTS
        - LEARNING_RATE
        - AUGMENTATION
        - BATCH_SIZE 
        - EPOCHS 

      outs:
        - trained_model/training/trained_model.keras

    
    evaluation:

      cmd: python src/cnn_classifier/pipeline/Stage04_model_evaluation_mlflow.py

      deps:
        - src/cnn_classifier/pipeline/Stage04_model_evaluation_mlflow.py
        - config/config.yaml
        - artifacts/data_ingestion/data
        - trained_model/training/trained_model.keras
        - params.yaml

      params:
        - INPUT_SHAPE   # needed to prepare the test data for evaluation
        - BATCH_SIZE    # needed to prepare the test data for evaluation

      metrics:
        - ModelEvaluation_scores.json:
            cache: false


