# Dont use local system related absoulte path here, otherwise the app will throw error when we deploy it on the production server.
artifacts_root : artifacts

# Data Ingestion related configuration
data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://drive.google.com/file/d/1wLkVKHAOdJHmufkkgP65uGe3WLyu3WsO/view?usp=sharing
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


# Prepare Base Model related configuration
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  custom_base_model_path: artifacts/prepare_base_model/custom_base_model.keras
 
  
# Training related configuration
training:
  root_dir: trained_model/training
  trained_model_path: trained_model/training/trained_model.keras


